fixed error Assets/Editor/MyPluginPostProcessBuild.cs(5,19): error CS0234: The type or namespace name `iOS' does not exist in the namespace `UnityEditor'. Are you missing an assembly reference?